version: '3.1'

networks:
    my_network:
        driver: bridge

services:
    service-a:
        build:
            context: ./docker
            dockerfile: ./service-a/Dockerfile
        restart: always
        networks:
            - my_network
    service-b:
        build:
            context: ./docker
            dockerfile: ./service-b/Dockerfile
        restart: always
        networks:
            - my_network